// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/infra/grpc-client/asr.proto

package asrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioConfig_AudioEncoding int32

const (
	AudioConfig_AUDIO_ENCODING_UNSPECIFIED AudioConfig_AudioEncoding = 0
	AudioConfig_AUDIO_ENCODING_PCM_16BIT   AudioConfig_AudioEncoding = 1
	AudioConfig_AUDIO_ENCODING_OPUS        AudioConfig_AudioEncoding = 2
	AudioConfig_AUDIO_ENCODING_MP3         AudioConfig_AudioEncoding = 3
	AudioConfig_AUDIO_ENCODING_FLAC        AudioConfig_AudioEncoding = 4
)

// Enum value maps for AudioConfig_AudioEncoding.
var (
	AudioConfig_AudioEncoding_name = map[int32]string{
		0: "AUDIO_ENCODING_UNSPECIFIED",
		1: "AUDIO_ENCODING_PCM_16BIT",
		2: "AUDIO_ENCODING_OPUS",
		3: "AUDIO_ENCODING_MP3",
		4: "AUDIO_ENCODING_FLAC",
	}
	AudioConfig_AudioEncoding_value = map[string]int32{
		"AUDIO_ENCODING_UNSPECIFIED": 0,
		"AUDIO_ENCODING_PCM_16BIT":   1,
		"AUDIO_ENCODING_OPUS":        2,
		"AUDIO_ENCODING_MP3":         3,
		"AUDIO_ENCODING_FLAC":        4,
	}
)

func (x AudioConfig_AudioEncoding) Enum() *AudioConfig_AudioEncoding {
	p := new(AudioConfig_AudioEncoding)
	*p = x
	return p
}

func (x AudioConfig_AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioConfig_AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_infra_grpc_client_asr_proto_enumTypes[0].Descriptor()
}

func (AudioConfig_AudioEncoding) Type() protoreflect.EnumType {
	return &file_internal_infra_grpc_client_asr_proto_enumTypes[0]
}

func (x AudioConfig_AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioConfig_AudioEncoding.Descriptor instead.
func (AudioConfig_AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_internal_infra_grpc_client_asr_proto_rawDescGZIP(), []int{1, 0}
}

type RecognizeStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*RecognizeStreamRequest_Config
	//	*RecognizeStreamRequest_Chunk
	Data          isRecognizeStreamRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeStreamRequest) Reset() {
	*x = RecognizeStreamRequest{}
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeStreamRequest) ProtoMessage() {}

func (x *RecognizeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeStreamRequest.ProtoReflect.Descriptor instead.
func (*RecognizeStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_client_asr_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeStreamRequest) GetData() isRecognizeStreamRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecognizeStreamRequest) GetConfig() *AudioConfig {
	if x != nil {
		if x, ok := x.Data.(*RecognizeStreamRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *RecognizeStreamRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*RecognizeStreamRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isRecognizeStreamRequest_Data interface {
	isRecognizeStreamRequest_Data()
}

type RecognizeStreamRequest_Config struct {
	Config *AudioConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type RecognizeStreamRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*RecognizeStreamRequest_Config) isRecognizeStreamRequest_Data() {}

func (*RecognizeStreamRequest_Chunk) isRecognizeStreamRequest_Data() {}

type AudioConfig struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Encoding      AudioConfig_AudioEncoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=asr.v1.AudioConfig_AudioEncoding" json:"encoding,omitempty"`
	SampleRate    int32                     `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioConfig) Reset() {
	*x = AudioConfig{}
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioConfig) ProtoMessage() {}

func (x *AudioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioConfig.ProtoReflect.Descriptor instead.
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_client_asr_proto_rawDescGZIP(), []int{1}
}

func (x *AudioConfig) GetEncoding() AudioConfig_AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioConfig_AUDIO_ENCODING_UNSPECIFIED
}

func (x *AudioConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type RecognizeStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeStreamResponse) Reset() {
	*x = RecognizeStreamResponse{}
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeStreamResponse) ProtoMessage() {}

func (x *RecognizeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_client_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeStreamResponse.ProtoReflect.Descriptor instead.
func (*RecognizeStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_client_asr_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeStreamResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_infra_grpc_client_asr_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_client_asr_proto_rawDesc = "" +
	"\n" +
	"$internal/infra/grpc-client/asr.proto\x12\x06asr.v1\"g\n" +
	"\x16RecognizeStreamRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x13.asr.v1.AudioConfigH\x00R\x06config\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x87\x02\n" +
	"\vAudioConfig\x12=\n" +
	"\bencoding\x18\x01 \x01(\x0e2!.asr.v1.AudioConfig.AudioEncodingR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"\x97\x01\n" +
	"\rAudioEncoding\x12\x1e\n" +
	"\x1aAUDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUDIO_ENCODING_PCM_16BIT\x10\x01\x12\x17\n" +
	"\x13AUDIO_ENCODING_OPUS\x10\x02\x12\x16\n" +
	"\x12AUDIO_ENCODING_MP3\x10\x03\x12\x17\n" +
	"\x13AUDIO_ENCODING_FLAC\x10\x04\"-\n" +
	"\x17RecognizeStreamResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2d\n" +
	"\n" +
	"ASRService\x12V\n" +
	"\x0fRecognizeStream\x12\x1e.asr.v1.RecognizeStreamRequest\x1a\x1f.asr.v1.RecognizeStreamResponse(\x010\x01B-Z+github.com/Tyulenb/grpc-client/asr/v1;asrv1b\x06proto3"

var (
	file_internal_infra_grpc_client_asr_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_client_asr_proto_rawDescData []byte
)

func file_internal_infra_grpc_client_asr_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_client_asr_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_client_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_client_asr_proto_rawDesc), len(file_internal_infra_grpc_client_asr_proto_rawDesc)))
	})
	return file_internal_infra_grpc_client_asr_proto_rawDescData
}

var file_internal_infra_grpc_client_asr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_infra_grpc_client_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_infra_grpc_client_asr_proto_goTypes = []any{
	(AudioConfig_AudioEncoding)(0),  // 0: asr.v1.AudioConfig.AudioEncoding
	(*RecognizeStreamRequest)(nil),  // 1: asr.v1.RecognizeStreamRequest
	(*AudioConfig)(nil),             // 2: asr.v1.AudioConfig
	(*RecognizeStreamResponse)(nil), // 3: asr.v1.RecognizeStreamResponse
}
var file_internal_infra_grpc_client_asr_proto_depIdxs = []int32{
	2, // 0: asr.v1.RecognizeStreamRequest.config:type_name -> asr.v1.AudioConfig
	0, // 1: asr.v1.AudioConfig.encoding:type_name -> asr.v1.AudioConfig.AudioEncoding
	1, // 2: asr.v1.ASRService.RecognizeStream:input_type -> asr.v1.RecognizeStreamRequest
	3, // 3: asr.v1.ASRService.RecognizeStream:output_type -> asr.v1.RecognizeStreamResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_client_asr_proto_init() }
func file_internal_infra_grpc_client_asr_proto_init() {
	if File_internal_infra_grpc_client_asr_proto != nil {
		return
	}
	file_internal_infra_grpc_client_asr_proto_msgTypes[0].OneofWrappers = []any{
		(*RecognizeStreamRequest_Config)(nil),
		(*RecognizeStreamRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_client_asr_proto_rawDesc), len(file_internal_infra_grpc_client_asr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_client_asr_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_client_asr_proto_depIdxs,
		EnumInfos:         file_internal_infra_grpc_client_asr_proto_enumTypes,
		MessageInfos:      file_internal_infra_grpc_client_asr_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_client_asr_proto = out.File
	file_internal_infra_grpc_client_asr_proto_goTypes = nil
	file_internal_infra_grpc_client_asr_proto_depIdxs = nil
}
